# Dictionnaire des traductions
TRANSLATIONS = {
    "fr": {
        "title": "Installation de TrackMyPrompt",
        "welcome": "Bienvenue dans l'installeur de TrackMyPrompt",
        "language_selection": "Sélection de la langue",
        "choose_language": "Choisissez votre langue :",
        "continue": "Continuer",
        "license": "Licence d'utilisation",
        "accept": "J'accepte",
        "installation": "Installation des dépendances",
        "wait_message": "Cela peut prendre quelques minutes...",
        "install": "Installer",
        "completed": "Installation terminée",
        "thanks": "Merci d'avoir installé TrackMyPrompt !",
        "quit": "Quitter",
        "error": "Erreur",
        "command_failed": "La commande a échoué :\n{}"
    },
    "en": {
        "title": "TrackMyPrompt Installation",
        "welcome": "Welcome to TrackMyPrompt installer",
        "language_selection": "Language Selection",
        "choose_language": "Choose your language:",
        "continue": "Continue",
        "license": "License Agreement",
        "accept": "I Accept",
        "installation": "Dependencies Installation",
        "wait_message": "This may take a few minutes...",
        "install": "Install",
        "completed": "Installation Completed",
        "thanks": "Thank you for installing TrackMyPrompt!",
        "quit": "Quit",
        "error": "Error",
        "command_failed": "Command failed:\n{}"
    },
    "es": {
        "title": "Instalación de TrackMyPrompt",
        "welcome": "Bienvenido al instalador de TrackMyPrompt",
        "language_selection": "Selección de idioma",
        "choose_language": "Elige tu idioma:",
        "continue": "Continuar",
        "license": "Acuerdo de licencia",
        "accept": "Acepto",
        "installation": "Instalación de dependencias",
        "wait_message": "Esto puede tomar algunos minutos...",
        "install": "Instalar",
        "completed": "Instalación completada",
        "thanks": "¡Gracias por instalar TrackMyPrompt!",
        "quit": "Salir",
        "error": "Error",
        "command_failed": "El comando falló:\n{}"
    },
    "de": {
        "title": "TrackMyPrompt Installation",
        "welcome": "Willkommen zum TrackMyPrompt Installer",
        "language_selection": "Sprachauswahl",
        "choose_language": "Wählen Sie Ihre Sprache:",
        "continue": "Weiter",
        "license": "Lizenzvereinbarung",
        "accept": "Ich akzeptiere",
        "installation": "Installation der Abhängigkeiten",
        "wait_message": "Dies kann einige Minuten dauern...",
        "install": "Installieren",
        "completed": "Installation abgeschlossen",
        "thanks": "Vielen Dank für die Installation von TrackMyPrompt!",
        "quit": "Beenden",
        "error": "Fehler",
        "command_failed": "Befehl fehlgeschlagen:\n{}"
    },
    "it": {
        "title": "Installazione di TrackMyPrompt",
        "welcome": "Benvenuto nell'installer di TrackMyPrompt",
        "language_selection": "Selezione della lingua",
        "choose_language": "Scegli la tua lingua:",
        "continue": "Continua",
        "license": "Accordo di licenza",
        "accept": "Accetto",
        "installation": "Installazione delle dipendenze",
        "wait_message": "Questo potrebbe richiedere alcuni minuti...",
        "install": "Installa",
        "completed": "Installazione completata",
        "thanks": "Grazie per aver installato TrackMyPrompt!",
        "quit": "Esci",
        "error": "Errore",
        "command_failed": "Comando fallito:\n{}"
    },
    "pt": {
        "title": "Instalação do TrackMyPrompt",
        "welcome": "Bem-vindo ao instalador do TrackMyPrompt",
        "language_selection": "Seleção de idioma",
        "choose_language": "Escolha seu idioma:",
        "continue": "Continuar",
        "license": "Acordo de licença",
        "accept": "Eu aceito",
        "installation": "Instalação de dependências",
        "wait_message": "Isso pode levar alguns minutos...",
        "install": "Instalar",
        "completed": "Instalação concluída",
        "thanks": "Obrigado por instalar o TrackMyPrompt!",
        "quit": "Sair",
        "error": "Erro",
        "command_failed": "Comando falhou:\n{}"
    },
    "ru": {
        "title": "Установка TrackMyPrompt",
        "welcome": "Добро пожаловать в установщик TrackMyPrompt",
        "language_selection": "Выбор языка",
        "choose_language": "Выберите ваш язык:",
        "continue": "Продолжить",
        "license": "Лицензионное соглашение",
        "accept": "Я принимаю",
        "installation": "Установка зависимостей",
        "wait_message": "Это может занять несколько минут...",
        "install": "Установить",
        "completed": "Установка завершена",
        "thanks": "Спасибо за установку TrackMyPrompt!",
        "quit": "Выход",
        "error": "Ошибка",
        "command_failed": "Команда не выполнена:\n{}"
    },
    "zh": {
        "title": "TrackMyPrompt 安装程序",
        "welcome": "欢迎使用 TrackMyPrompt 安装程序",
        "language_selection": "语言选择",
        "choose_language": "选择您的语言：",
        "continue": "继续",
        "license": "许可协议",
        "accept": "我接受",
        "installation": "依赖项安装",
        "wait_message": "这可能需要几分钟时间...",
        "install": "安装",
        "completed": "安装完成",
        "thanks": "感谢您安装 TrackMyPrompt！",
        "quit": "退出",
        "error": "错误",
        "command_failed": "命令失败：\n{}"
    },
    "ja": {
        "title": "TrackMyPrompt インストール",
        "welcome": "TrackMyPrompt インストーラーへようこそ",
        "language_selection": "言語選択",
        "choose_language": "言語を選択してください：",
        "continue": "続行",
        "license": "ライセンス契約",
        "accept": "同意します",
        "installation": "依存関係のインストール",
        "wait_message": "数分かかる場合があります...",
        "install": "インストール",
        "completed": "インストール完了",
        "thanks": "TrackMyPrompt をインストールしていただき、ありがとうございます！",
        "quit": "終了",
        "error": "エラー",
        "command_failed": "コマンドが失敗しました：\n{}"
    }
}

# Liste des langues disponibles
LANGUAGES = {
    "Français": "fr",
    "English": "en",
    "Español": "es",
    "Deutsch": "de",
    "Italiano": "it",
    "Português": "pt",
    "Русский": "ru",
    "中文": "zh",
    "日本語": "ja"
}